name: Deploy to GitHub Pages

on:
    push:
        branches: ["main"]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build-website:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm build
            - uses: actions/upload-artifact@v3
              with:
                  name: build-website
                  path: dist
                  retention-days: 1
    deploy:
        runs-on: ubuntu-latest
        needs: [build-website]
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/configure-pages@v3
            - uses: actions/download-artifact@v3
              with:
                  name: build-website
                  path: "."
            - uses: actions/upload-pages-artifact@v2
              with:
                  path: "."
            - id: deployment
              uses: actions/deploy-pages@v2
